# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: locations